#
# Blog Settings
#
author: Phil Haack
description: You've been Haacked and you like it
url: http://buin2009.github.io
title: You've Been Haacked
subtitle: ...and you like it
gravatar_url: 
subscribe_rss: http://feeds.ha

# Github repositories
github_user: buin2009
github_repo_url: https://github.com/buin2009/

# Twitter
twitter_user: haacked
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: haacked
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: 


#
# Jekyll Settings
#
markdown: redcarpet
pygments: true
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories
